AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your downloadfunction.
Parameters:
 contentHandling:
 Type: String
Resources:
  audGeneratePSURL:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: aud-groot-downloadfiles/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 1536
      Timeout: 15
      Environment:
        Variables:
          BUCKET_NAME: 001audible-groot-archive
          REGION: us-east-1
          IDENTITY_POOL_ID: us-east-1:5c3d9a07-696d-46a6-9238-1477ab36f541
          LOGIN_URL: arn:aws:iam::942158337222:saml-provider/SalesForce
          FILE_EXTENSION: .zip
          EXPIRY_TIME: 600
    apiGateway:
      Type: "AWS::ApiGateway::RestApi"
      Properties:
        Name: "aud-groot-downloadfiles"
        Description: "API gateway to call lambda to pull the file from S3"
    apiGatewayRootMethod:
      Type: "AWS::ApiGateway::Method"
      Properties:
        AuthorizationType: "NONE"
        HttpMethod: "POST"
        Integration:
          IntegrationHttpMethod: "POST"
          Type: "AWS_PROXY"
          Uri: !Sub
            - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
            - lambdaArn: !GetAtt "lambdaFunction.Arn"
          IntegrationResponses:
            - ContentHandling: !Ref contentHandling
              StatusCode: 302 
        ResourceId: !GetAtt "apiGateway.RootResourceId"
        RestApiId: !Ref "apiGateway"
    apiGatewayDeployment:
      Type: "AWS::ApiGateway::Deployment"
      DependsOn:
        - "apiGatewayRootMethod"
      Properties:
        RestApiId: !Ref "apiGateway"
        StageName: !Ref "apiGatewayStageName
